use_frameworks!

platform :ios, '17.5'

target 'ObjectiveSocketIO_Example' do
  pod 'ObjectiveSocketIO', :path => '../'

  target 'ObjectiveSocketIO_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.5'
               end
          end
   end
end